# Generated by Django 2.1.3 on 2019-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190115_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='', upload_to='products/products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='', upload_to='products/products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='', upload_to='products/products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(default='', upload_to='products/products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(default='', upload_to='products/products/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default='', upload_to='products/products_main/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
