# Generated by Django 2.1.3 on 2019-01-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190115_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='sub_description',
        ),
    ]
