# Generated by Django 2.1.3 on 2019-01-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='url',
            new_name='urls',
        ),
    ]
