# Generated by Django 2.1.3 on 2019-02-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190125_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerimage',
            field=models.ImageField(upload_to='products/banner/%Y/%m/%d'),
        ),
    ]
