# Generated by Django 2.1.3 on 2019-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190213_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='bannerimage',
            new_name='bannerimage1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='urls',
            new_name='urls1',
        ),
        migrations.AddField(
            model_name='banner',
            name='bannerimage2',
            field=models.ImageField(default='', upload_to='products/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='bannerimage3',
            field=models.ImageField(default='', upload_to='products/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='bannerimage4',
            field=models.ImageField(default='', upload_to='products/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='bannerimage5',
            field=models.ImageField(default='', upload_to='products/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='bannerimage6',
            field=models.ImageField(default='', upload_to='products/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urls2',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urls3',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urls4',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urls5',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urls6',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
