# Generated by Django 2.1.3 on 2019-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_price_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='price_sale (฿)'),
            preserve_default=False,
        ),
    ]
