# Generated by Django 2.1.3 on 2019-02-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_price_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sale',
        ),
    ]
