# Generated by Django 2.1.3 on 2019-02-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
