# Generated by Django 2.1.3 on 2019-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(verbose_name='price_sale (฿)'),
        ),
    ]
