# Generated by Django 2.1.3 on 2019-02-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20190222_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(verbose_name='price_sale (฿)'),
        ),
    ]
